export const CODE_API_URL = '/contact/v1/code';
export const UPLOAD_FILE_LIST_API_URL = '/contact/v1/file/upload';
export const DOWNLOAD_FILE_LIST_API_URL = '/contact/v1/file/download';
export const ADD_VOC_API_URL = '/contact/v1/voc';
export const FOOTER_ADDRESS_URL = '/api/v1/footer-wd-1?_format=json';
export const FOOTER_MENU_URL = '/api/v1/menu_custom_api?menu_name=footer';
export const FOOTER_CONTACT_URL = '/api/v1/footer-wd-3?_format=json';
export const FOOTER_SNS_URL = '/api/v1/footer-wd-4?_format=json';
export const PRIVACY_POLICY_URL = '/api/v1/about-us/privacy-policy';
